language: node_js
node_js:
  - 16

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed karim199260/udagram-api-feed:v1
  - docker tag udagram-api-feed karim199260/udagram-api-user:v1
  - docker tag udagram-api-feed karim199260/udagram-frontend:v1
  - docker tag udagram-api-feed karim199260/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push karim199260/udagram-api-feed:v1
  - docker push karim199260/udagram-api-user:v1
  - docker push karim199260/udagram-frontend:v1
  - docker push karim199260/udagram-reverseproxy:v1